name: Deployment-GCP(VM)

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend-vite

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend-vite/package-lock.json

      - name: Install Dependency
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload disto to VM in GCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "frontend-vite/dist/*"
          target: "/tmp/portfolio-dist"
